### ISSUE TITLE
ruby problems

### ISSUE THREAD

**Issue by rops** [StanHutcheon/SiriAuth#2]
when I run "rvmsudo ruby start.rb" I get this errors:

/home/daniele/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- tweakSiri (LoadError)
    from /home/daniele/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from start.rb: 2 :in < main >

Any ideas about how to solve it?

**Comment by alnandr** [comment]
I am also experiencing a similar issue:

/usr/local/rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- tweakSiri (LoadError)
    from /usr/local/rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from ./start.rb:2:in `<main>'

From the looks of it, it looks like Ruby is interfering with an older version of Ruby but I ensured that I typed in "rvm use 1.9.3 --default" when installing it. Also, both ports (443 and 53) aren't being used by another process.

This is the second time I attempt at installing this. The first time was on CentOS 5, this time on Ubuntu. It's the same exact error every time, and it's preventing me from launching the actual Siri server.

**Comment by mcgeezy** [comment]
I had the same issue.  My fix was:

export RUBYLIB=/path/to/SiriAuth

**Comment by ghost** [comment]
thanks mcgeezy in Debian squeeze the same probem

**Comment by dionysius** [comment]
thanks @mcgeezy ! fix in centos 5.7 also worked

**Comment by ipadshouse** [comment]
export RUBYLIB=/path/to/SiriAuth doesn't fix the error in Ubuntu 11.10

**Comment by mcgeezy** [comment]
@ipadshouse weird, that's what I'm using.
are you replacing /path/to/ with the actual path to SiriAuth?  It won't work otherwise.

**Comment by ipadshouse** [comment]
:-) sure I replace it with my working SiriAuth path. I am going to reinstall ubuntu and make a new clean ruby installation
